"""add origin and handover_date to devices

Revision ID: 0197d7f9044b
Revises: f62da7e0a4b6
Create Date: 2026-07-18 15:11:05.154185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0197d7f9044b'
down_revision: Union[str, Sequence[str], None] = 'f62da7e0a4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('origin', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('handover_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'handover_date')
    op.drop_column('devices', 'origin')
    # ### end Alembic commands ###
