"""make_inventory_item_id_nullable_add_device_id_to_berita_acara

Revision ID: 0a4020f56548
Revises: 196aa8b072c0
Create Date: 2026-07-18 17:19:20.210179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4020f56548'
down_revision: Union[str, Sequence[str], None] = '196aa8b072c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('berita_acara', sa.Column('device_id', sa.UUID(), nullable=True))
    op.alter_column('berita_acara', 'inventory_item_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_berita_acara_device_id'), 'berita_acara', ['device_id'], unique=False)
    op.create_foreign_key(None, 'berita_acara', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'berita_acara', type_='foreignkey')
    op.drop_index(op.f('ix_berita_acara_device_id'), table_name='berita_acara')
    op.alter_column('berita_acara', 'inventory_item_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('berita_acara', 'device_id')
    # ### end Alembic commands ###
