"""add_berita_acara_table

Revision ID: 196aa8b072c0
Revises: 0197d7f9044b
Create Date: 2026-07-18 16:18:35.357689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196aa8b072c0'
down_revision: Union[str, Sequence[str], None] = '0197d7f9044b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('berita_acara',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('lab_id', sa.UUID(), nullable=False),
    sa.Column('keterangan_kerusakan', sa.String(), nullable=False),
    sa.Column('keterangan_perbaikan', sa.String(), nullable=True),
    sa.Column('status_penanganan', sa.Enum('perlu_perbaikan', 'telah_diperbaiki', 'alat_baru', name='statuspenanganan'), nullable=False),
    sa.Column('tanggal_lapor', sa.DateTime(), nullable=False),
    sa.Column('tanggal_selesai', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_berita_acara_inventory_item_id'), 'berita_acara', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_berita_acara_lab_id'), 'berita_acara', ['lab_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_berita_acara_lab_id'), table_name='berita_acara')
    op.drop_index(op.f('ix_berita_acara_inventory_item_id'), table_name='berita_acara')
    op.drop_table('berita_acara')
    # ### end Alembic commands ###
