"""dynamic_lab_type

Revision ID: 34522dc15ea8
Revises: 6f29b5cdff56
Create Date: 2026-07-19 00:41:57.596585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34522dc15ea8'
down_revision: Union[str, Sequence[str], None] = '6f29b5cdff56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    lab_categories_table = op.create_table('lab_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_categories_name'), 'lab_categories', ['name'], unique=True)
    op.create_index(op.f('ix_lab_categories_slug'), 'lab_categories', ['slug'], unique=True)
    
    # Need to cast enum to varchar explicitly
    op.execute("ALTER TABLE labs ALTER COLUMN type TYPE VARCHAR USING type::text")
    op.execute("DROP TYPE IF EXISTS labtype")
    
    # Seed default data
    import uuid
    op.bulk_insert(
        lab_categories_table,
        [
            {"id": uuid.uuid4(), "name": "Laboratorium Komputer", "slug": "komputer"},
            {"id": uuid.uuid4(), "name": "Laboratorium Teknik", "slug": "teknik"},
            {"id": uuid.uuid4(), "name": "Laboratorium Kedokteran", "slug": "kedokteran"},
            {"id": uuid.uuid4(), "name": "Laboratorium Bahasa", "slug": "bahasa"},
            {"id": uuid.uuid4(), "name": "Laboratorium Jaringan", "slug": "jaringan"},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labs', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('komputer', 'teknik', 'kedokteran', name='labtype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_lab_categories_slug'), table_name='lab_categories')
    op.drop_index(op.f('ix_lab_categories_name'), table_name='lab_categories')
    op.drop_table('lab_categories')
    # ### end Alembic commands ###
