"""Add LabBorrowing models

Revision ID: 6f29b5cdff56
Revises: 0a4020f56548
Create Date: 2026-07-18 23:59:17.090666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f29b5cdff56'
down_revision: Union[str, Sequence[str], None] = '0a4020f56548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_borrowings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_npm', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('num_people', sa.Integer(), nullable=False),
    sa.Column('lab_type', sa.String(), nullable=False),
    sa.Column('lab_name', sa.String(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='borrowingstatus'), nullable=False),
    sa.Column('booking_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_borrowings_booking_id'), 'lab_borrowings', ['booking_id'], unique=True)
    op.create_table('lab_borrowing_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lab_borrowing_id', sa.UUID(), nullable=False),
    sa.Column('npm', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lab_borrowing_id'], ['lab_borrowings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_borrowing_members')
    op.drop_index(op.f('ix_lab_borrowings_booking_id'), table_name='lab_borrowings')
    op.drop_table('lab_borrowings')
    # ### end Alembic commands ###
