"""Add is_global to install_keys

Revision ID: 79cc027e0fce
Revises: 819943562d5b
Create Date: 2026-07-12 12:03:48.242462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79cc027e0fce'
down_revision: Union[str, Sequence[str], None] = '819943562d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('install_keys', sa.Column('is_global', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('install_keys', 'is_global')
    # ### end Alembic commands ###
