"""add ip_address to devices

Revision ID: f62da7e0a4b6
Revises: 79cc027e0fce
Create Date: 2026-07-13 08:42:21.912481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62da7e0a4b6'
down_revision: Union[str, Sequence[str], None] = '79cc027e0fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('ip_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'ip_address')
    # ### end Alembic commands ###
