"""Add lab schedule table

Revision ID: fa4988cb2994
Revises: 34522dc15ea8
Create Date: 2026-07-19 08:38:23.261065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4988cb2994'
down_revision: Union[str, Sequence[str], None] = '34522dc15ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lab_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('lecturer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_schedules_id'), 'lab_schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_schedules_id'), table_name='lab_schedules')
    op.drop_table('lab_schedules')
    # ### end Alembic commands ###
